image: kaiwinter/docker-java8-maven

stages:
  - build_and_test
  - deploy

build_prj:
  type: build_and_test
  script: "xhost + && cd parentprj && mvn install -B && cat proud-coverage/target/coverage-report/html/jacoco-multi/index.html"

staging:
  type: deploy
  script:
  - "echo deploying "
  only:
  - master